import type { Metadata } from "next";
import ExplorerContent from "./_components/ExplorerContent";
import TrendListContainer from "./_components/TrendList/container";

export const metadata: Metadata = {
  title: "Explorer / twitter-clone",
  description: "Generated by Next.js",
};

export default async function Explorer() {
  const trendListComponent = await TrendListContainer();
  return <ExplorerContent trendListComponent={trendListComponent} />;
}
