import Tabs from "@/app/(3col)/_components/Tabs";
import { get } from "@/lib/utils/fetcher";
import type { SuccessResponse, User } from "@/types";
import type { Metadata } from "next";
import ForyouTab from "./_components/FollowingTab";
import FollowingTab from "./_components/ForyouTab";
import { TAB_FOR_YOU, tabs } from "./_data";

export const metadata: Metadata = {
  title: "Home / twitter-clone",
  description: "Generated by Next.js",
};

export default async function Home() {
  const { data: user } = await get<SuccessResponse<User>>({
    url: "/api/users/me",
  });
  return (
    <Tabs
      tabs={tabs}
      defaultValue={TAB_FOR_YOU}
      tabsProps={{ className: "border-r border-l min-h-screen" }}
      listProps={{ className: "sticky top-0 z-1 bg-white opacity-95" }}
    >
      <ForyouTab user={user} />
      <FollowingTab user={user} />
    </Tabs>
  );
}
