import FollowersPostList from "@/app/(3col)/home/_components/FollowersPostList";
import PostInputForm from "@/app/(3col)/home/_components/PostInputForm";
import PostList from "@/app/(3col)/home/_components/PostList";
import Tabs, { TabA, TabB } from "@/app/(3col)/home/_components/Tabs";
import type { Metadata } from "next";
import { Suspense } from "react";
import Loader from "../_components/Loader";

export const metadata: Metadata = {
  title: "Home / twitter-clone",
  description: "Generated by Next.js",
};

export default function Home() {
  return (
    <Tabs>
      <TabA>
        <PostInputForm />
        <PostList />
      </TabA>
      <TabB>
        <PostInputForm />
        <Suspense fallback={<Loader />}>
          <FollowersPostList />
        </Suspense>
      </TabB>
    </Tabs>
  );
}
