import Tabs, { TabA, TabB } from "@/app/(3col)/home/_components/Tabs";
import PostInput from "@/app/(3col)/home/_containers/PostInput";
import PostList from "@/app/(3col)/home/_containers/PostList";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Home / X-clone",
	description: "Generated by Next.js",
};

export default function Home() {
	return (
		<Tabs>
			<TabA>
				<PostInput />
				<PostList />
			</TabA>
			<TabB>
				<PostInput />
				<PostList />
			</TabB>
		</Tabs>
	);
}
