import { BackgroundImage, Box } from "@/lib/mantine/core";
import type { Metadata } from "next";
import HeaderNavigation from "./_components/HeaderNavigation";
import ProfileBody from "./_components/ProfileBody";
import ProfileHeader from "./_components/ProfileHeader";
import ProfileTabs from "./_components/ProfileTabs";

export const metadata: Metadata = {
  title: "Profile / twitter-clone",
  description: "Generated by Next.js",
};

export default function ProfilePage({
  params,
}: { params: Promise<{ id: string }> }) {
  return (
    <div className="min-h-screen border-r border-l">
      <HeaderNavigation promise={params} />
      <BackgroundImage
        component="a"
        src="/images/banner.png"
        className="!bg-cover !bg-no-repeat !z-0"
      >
        <Box h={200} />
      </BackgroundImage>
      <ProfileHeader promise={params} />
      <ProfileBody promise={params} />
      <ProfileTabs promise={params} />
    </div>
  );
}
