import type { Metadata } from "next";
import Home from "./client";

export const metadata: Metadata = {
	title: "Home / X-clone",
	description: "Generated by Next.js",
};

export default function HomePage() {
	return <Home />;
}
