import HeaderBox from "@/app/_components/HeaderBox";
import Tabs, { TabA, TabB } from "@/app/home/_components/Tabs";
import PostInput from "@/app/home/_containers/PostInput";
import PostList from "@/app/home/_containers/PostList";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Home / X-clone",
	description: "Generated by Next.js",
};

export default function Home() {
	return (
		<main>
			<HeaderBox>
				<Tabs>
					<TabA>
						<PostInput />
						<PostList />
					</TabA>
					<TabB>
						<PostInput />
						<PostList />
					</TabB>
				</Tabs>
			</HeaderBox>
		</main>
	);
}
